version: '3.8'

services:
  liplock-app:
    container_name: liplock-server
    build: .
    ports:
      - "8080:8000"
    volumes:
      - "./Original Tracks:/app/Original Tracks"
      - "./Instrumental Tracks:/app/Instrumental Tracks"
    restart: unless-stopped